version: '3.9'

services:
  web:
    build: .
    container_name: car_app_web
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2
    container_name: car_app_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  celery_worker:
    build: .
    container_name: car_app_celery_worker
    command: celery -A tasks.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started

  celery_beat:
    build: .
    container_name: car_app_celery_beat
    command: celery -A tasks.celery_worker.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
