"""Allow null fields for car

Revision ID: 96687780130a
Revises: b045ffee6c40
Create Date: 2025-08-08 15:08:48.387181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96687780130a'
down_revision = 'b045ffee6c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
