"""Allow NULL for objectId

Revision ID: ddbafb095ff9
Revises: 96687780130a
Create Date: 2025-08-11 11:37:46.605585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbafb095ff9'
down_revision = '96687780130a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('objectId',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('objectId',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
